### PR TITLE
Wait 180 seconds until database is ready or die.

### PR DESCRIPTION
**Pull request by Niko9911**
Wait 30 seconds until database is ready otherwise exit with error code of 1.

### CODE REVIEW

**Comment by dunglas** [comment]
It's 15 seconds isn't it?

**Comment by Niko9911** [comment]
Yes, and according to my testing It needs to be raised to 90 seconds at least, so 120 to be sure. I will make a fix.

**Comment by Niko9911** [comment]
Just to be on safe side, I did put 180 seconds. 

This timeout idea is anyways getting our deployments stuck. Instead of getting stuck due a configuration mistake, it will exit unclean.

**Comment by teohhanhui** [comment]
This is not the correct approach. Please use the healthcheck feature of your container orchestrator.

**Comment by Niko9911** [comment]
@teohhanhui Please show me how you do it in docker-compose and add it into the repo. 

Youre now expecting everyone to run this in kubernetes or what?

That is totally not understandable point of view.

**Comment by teohhanhui** [comment]
But we could add a default `HEALTHCHECK` instruction to our `php` image indeed. It'd require `cgi-fcgi` (available from https://pkgs.alpinelinux.org/package/v3.10/main/x86_64/fcgi).

**Comment by teohhanhui** [comment]
> Youre now expecting everyone to run this in kubernetes or what?

No. You can use healthcheck in Docker Compose too. :smile:

> Please show me how you do it in docker-compose and add it into the repo.

Yeah, we should do that.

**Comment by teohhanhui** [comment]
You can find an example here: https://github.com/renatomefi/php-fpm-healthcheck

**Pull request closed without merging**
