### PR TITLE
Fix Book::$title fixture generator

### PR DESCRIPTION
**Pull request by dunglas**
ping @theofidry

### CODE REVIEW

**Comment by theofidry** [comment]
👍

**Comment by teohhanhui** [comment]
We might want to add a custom faker to convert it to title case and strip off the period (`.`) at the end.

**Comment by dunglas** [comment]
I was reluctant to add the fixture bundle in the standard edition but I thin it's definitely not the place to add things like custom faker generator.

However it can be added in the demo (the app illustrating the getting started guide) if anybody care.

**Comment by teohhanhui** [comment]
I agree. We should remove all fixtures from the standard edition.

**Pull request merged**
