### PR TITLE
Specify version of apcu to be installed

### PR DESCRIPTION
**Pull request by teohhanhui**
Due to https://pear.php.net/bugs/bug.php?id=21008

### CODE REVIEW

**Comment by jderusse** [comment]
Given the version of PHP is fixed by `FROM php:7.0-apache`, the Dockerfile is not affected by this bug.

By fixing the version of APCU, we'll have to follow a third party project to backport the change in this project each time a new version of APCU is released.

**Comment by teohhanhui** [comment]
@jderusse Sorry, I don't get what you mean... I've just encountered this bug, hence the fix.

**Comment by teohhanhui** [comment]
The PEAR bug says that the PHP version dependency is not being taken into consideration when selecting the package version.

**Comment by vincentchalamon** [comment]
@teohhanhui Can you update this PR about StyleCI please ?

**Comment by teohhanhui** [comment]
@dunglas You have to turn off the Travis build for this repo for now...

**Comment by dunglas** [comment]
Can this bug be close @teohhanhui (Travis is green right now)?

**Comment by teohhanhui** [comment]
@dunglas It's only working right now. It will fail again when they release another 4.x version of apcu.

**Comment by dunglas** [comment]
So can we merge it?

**Comment by teohhanhui** [comment]
@dunglas Yes. Updated to apcu v5.1.5

Sorry for the delay.

**Comment by dunglas** [comment]
Thank you @teohhanhui

**Pull request merged**
