### PR TITLE
Disable OPCache timestamps check in prod

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by dunglas** [comment]
Good idea, this PR probably needs to be updated now that we have a prod setup. /cc @teohhanhui

**Comment by Lctrs** [comment]
@dunglas seems like a rebasing is enough. The prod setup hasn't modified this part.

**Comment by soyuka** [comment]
feel free to merge @teohhanhui

**Comment by teohhanhui** [comment]
Something is definitely wrong here.

**Comment by teohhanhui** [comment]
Thanks @Lctrs! :tada:

**Pull request merged**
