### PR TITLE
[Docker] add standard streams

### PR DESCRIPTION
**Pull request by 20uf**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | no
| License       | MIT
| Doc PR        | no

Hello,

I added in the docker file the output of logs in console, I find absent and yet very practical to debug.

Regards

### CODE REVIEW

**Comment by dunglas** [comment]
Are you sure about your patch? Nginx logs are in the NGINX container, not in the PHP one. However maybe can we send Symfony logs to stderr.

**Comment by 20uf** [comment]
Hmm true.

Should logs be sent with monolog?

**Comment by teohhanhui** [comment]
http://stackoverflow.com/a/38501354/1529493

But I think we should log to both `var/logs/*.log` and `stderr`.

**Comment by 20uf** [comment]
I don't think it's appropriate for monolog to do that.
This is as part of a use with Docker, so it would actually be at the nginx container to do so.

**Comment by teohhanhui** [comment]
It needs to be done for each container. :smile:

For the Symfony logs, we can potentially do:

```sh
...
	&& ln -sf /dev/stderr var/logs/dev.log \
	&& ln -sf /dev/stderr var/logs/prod.log
```

See https://github.com/nginxinc/docker-nginx/blob/7b33a90d7441909664a920b0687db8d984ac314b/mainline/alpine/Dockerfile#L126-L128

**Pull request closed without merging**
