### PR TITLE
Delete .env

### PR DESCRIPTION
**Pull request by bendavies**
`.env` is in .gitignore, but not sure how this should work with `docker`, as it's referenced in `docker-compose.yaml`. WDYT @teohhanhui ?

### CODE REVIEW

**Comment by teohhanhui** [comment]
I think it shouldn't be in `.gitignore`.

**Comment by bendavies** [comment]
FYI, it's part of the framework bundle flex recipe. https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/manifest.json#L21

And the it ships a `.env.dist` which we do too.

**Comment by dunglas** [comment]
We reference the .env file in `docker-compose.yml`, we cannot delete it just like this. As long as Docker Compose doesn't provide support for dist file, we'll have to remove it from `.gitignore`.

**Comment by quentinus95** [comment]
You can reference the dist file in docker-compose using:
```
env_file:
      - ./.env.dist
```

**Comment by teohhanhui** [comment]
@quentinus95:

> You can reference the dist file in docker-compose

Unfortunately that means it ceases to be a "dist" file. :smile:

**Comment by teohhanhui** [comment]
Closing this one. I think we'll be able to do something about this after https://github.com/symfony/symfony/pull/28533 :smile:

**Pull request closed without merging**
