### PR TITLE
Fix Travis

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by teohhanhui** [comment]
Why?

**Comment by teohhanhui** [comment]
How do we make sure that we're using the correct version of Docker and Docker Compose going forward?

**Comment by dunglas** [comment]
Travis has upgraded its Ubuntu images and our test suite was broken. Removing specific versions actually fixes it. We should let Travis do its best when possible (here, its possible). I suggest to keep it as is to prevent breakages when Travis upgrade its setup.

**Comment by dunglas** [comment]
See https://travis-ci.org/api-platform/api-platform/builds/249307547?utm_source=github_status&utm_medium=notification for instance.

**Comment by teohhanhui** [comment]
Make sense...

**Pull request merged**
