### PR TITLE
Add debian php image version

### PR DESCRIPTION
**Pull request by d0niek**
Our app has to connect to HANA via odbc but our driver doesn't work with alpine so I had to use debian version.
Now we can switch distro by filling **arg** `ALIPNE` with `-alipne` or leave it empty.

### CODE REVIEW

**Comment by dunglas** [comment]
I fear that it adds complexity and increase the maintenance burden, wouldn't it better to explain this in the documentation?

**Comment by d0niek** [comment]
I think one maintenance problem is that when you install new `PERSISTENT_DEPS` or new lib for php extensions and there are different names for alpine and debian.

**Comment by soyuka** [comment]
> I fear that it adds complexity and increase the maintenance burden, wouldn't it better to explain this in the documentation?

:+1: at least it should be a new Dockerfile I don't think that we can maintain 2 oses at the same time

**Comment by teohhanhui** [comment]
This is the wrong approach.

**Pull request closed without merging**
