### PR TITLE
deps(react): update react scripts to latest version

### LINKED ISSUE #1263: Upgrade client/ and admin/ to react-scripts 3
A new version of Create React App is there.

### PR DESCRIPTION
**Pull request by dsuarezlogans**
This changes Update `react-scripts` dependency to latest version `3.1.2`

Fixes #1263 

@douglas @alanpoulain

### CODE REVIEW

**Comment by alanpoulain** [comment]
Related PR: https://github.com/api-platform/api-platform/pull/1266

You didn't update the `package.lock` files and solve the issues related to this update.

**Comment by dunglas** [comment]
And there is more work to do to make it running. The JS must be migrated with the one generated by Create React App 3 too.

**Comment by dsuarezlogans** [comment]
Hi, sure I'll push the `yarn.lock` with the updates but I do not encounter any issues after the update, I ran `docker-composer up` and was able to to interact with the app in localhost without any issues.

> And there is more work to do to make it running. The JS must be migrated with the one generated by Create React App 3 too.

@dunglas Not sure what you mean with this, I'm this is my first contribution, can you please explain me what you mean with that?

**Comment by dunglas** [comment]
Thanks @dsuarezlogans!!

**Pull request merged**
