### PR TITLE
fix the removing of authors and illustrators in the Book entity

### LINKED ISSUE #21: Error removing Persons from the Book entity
If I try to remove Persons from a Book I get the following error:

```
PUT http://localhost:9000/books/1
Content-Type: application/json
{
    "name": "Book 1", 
    "illustrator": [],
    "author": []
}
 -- response --
400 Bad Request
...
 "array_search() expects parameter 2 to be array, object given",
    "api-platform/src/AppBundle/Entity/Book.php", 106
    and 
    "api-platform/src/AppBundle/Entity/CreativeWork.php", 95,
...
```

This occurs because a Doctrine\ORM\PersistentCollection is passed as a second argument.

I fixed it and made a pull request #22

### PR DESCRIPTION
**Pull request by lubomir-haralampiev**
fixes #21 - Error removing Persons from the Book entity

### CODE REVIEW

**Comment by dunglas** [comment]
These file are automatically generated by https://github.com/api-platform/schema-generator. Can you open a PR to fix the generator first then regenerate files?

**Comment by lubomir-haralampiev** [comment]
OK, I'll take a look at it

**Comment by lubomir-haralampiev** [comment]
I fixed the generator https://github.com/api-platform/schema-generator/pull/32.

Though the url in the example schema https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-gozer/data/schema.rdfa includes a wrong content-type 'text/plain' in its response and the rdfa can not be parsed.
After serving the same data from my local machine using the correct content-type 'application/xhtml-xml' (according to http://www.w3.org/TR/xhtml-rdfa/) I was able to generate the files successfully.
Unfortunately I can't provide a public url with the correct content-type.

How to deal with it?
In my opinion this should be another issue.

**Comment by dunglas** [comment]
Yes it should. What about using this file: http://schema.org/docs/schema_org_rdfa.html?

**Comment by lubomir-haralampiev** [comment]
It works.
However genre and publisher have each two ranges defined:
genre - Text and URL
publisher - Organization and Person 

This causes the TypesGenerator::generateField to log an error:
```
[error] The property "genre" (type "CreativeWork") has several types. Using the first one.
[error] The property "publisher" (type "CreativeWork") has several types. Using the first one.
```

Though all types are generated properly.

**Comment by sroze** [comment]
I'm closing this PR as it's now out of date, and we should simply regenerate all the entities.

**Pull request closed without merging**
