### PR TITLE
Fix typo and update api dependencies for security:check

### PR DESCRIPTION
**Pull request by vincentchalamon**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by dunglas** [comment]
There is a bit more to do: https://github.com/api-platform/api-platform/pull/1477

**Comment by vincentchalamon** [comment]
@dunglas Maybe merge my PR into yours, about `docker-compose.yml` fix?

**Comment by dunglas** [comment]
Don't hesitate to take or close my PR. I'll not have the time today.

**Comment by vincentchalamon** [comment]
Closing in favor of #1477

**Pull request closed without merging**
