### PR TITLE
update-deps.sh: Run composer sync-recipes inside php container

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by maxhelias** [comment]
The command is not optimal in the container because it does not have the .git folder and Flex ask for each file override

**Comment by teohhanhui** [comment]
@maxhelias Uhh, because the `.git` directory is one level up. Hmm...

**Comment by teohhanhui** [comment]
Anyway, I think yeah, we don't need to change this, as it's only meant to be run by a maintainer.

**Comment by dunglas** [comment]
> Anyway, I think yeah, we don't need to change this, as it's only meant to be run by a maintainer.

Exactly, and it needs manual changes after the command has finished...

**Pull request closed without merging**
