### PR TITLE
Ensure that .env is always loaded in dev

### PR DESCRIPTION
**Pull request by cestcri**
I ran into this because APP_ENV is for whatever reason already set.
This change will lead to less code and increased readability.

### CODE REVIEW

**Comment by teohhanhui** [comment]
`api/.env` is loaded in `docker-compose.yml`. If you want to use Symfony `DotEnv`, you could just `composer require` it and comment out `APP_ENV` in `api/.env`

**Comment by cestcri** [comment]
Thanks for getting back to me @teohhanhui !
I'm not using Docker, not sure if this is a problem/not supported by the API platform? Maybe I should go for good old Symfony instead of API platform then?

**Comment by teohhanhui** [comment]
If you're not using Docker, then just do `composer req dotenv` :smile:

You shouldn't need to change anything else.

**Comment by teohhanhui** [comment]
Perhaps we should add this to the docs, if it's not already in there.

**Comment by cestcri** [comment]
I did do this (found this on the Symfony doc) but this won't fix the problem if your APP_ENV is already set to dev, which is for whatever reason my case. The suggested change makes this more robust and avoids imho users to struggle for nothing.

**Comment by teohhanhui** [comment]
-1

I understand your problem but I don't think the behaviour should be changed. If you think we could improve the documentation, please open a PR there. Also (more likely) for Symfony documentation.

**Comment by cestcri** [comment]
Fine with me, it was just a suggestion. It's fine on the Symfony doc, that's where I found the hint (which, as described, didn't solve the problem, and which is why I made this suggestion).

**Pull request closed without merging**
