### PR TITLE
Ensure git always uses LF for EOL in shell scripts

### LINKED ISSUE #326: Web container crashes on first install with docker
Following the documentation, I downloaded the last version (2.0.8 as I'm writing this) and was happy to have docker all configured to start working quickly.

But when running docker-compose up, the database container runs, then the web container crashes with the following message : 
docker-issue

web_1       |  [OK] All assets were successfully installed.
web_1       |
web_1       | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
web_1       | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
web_1       | + rm -f /var/run/apache2/apache2.pid
web_1       | + exec docker/apache/start_safe_perms -DFOREGROUND
web_1       | AH00526: Syntax error on line 1 of /etc/apache2/apache2.conf:
web_1       | Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
web_1       | Action '-DFOREGROUND' failed.
web_1       | The Apache error log may have more information.
hobbeesapi_web_1 exited with code 1

For information, I'm running it on windows 10 pro.

### PR DESCRIPTION
**Pull request by teohhanhui**
Should fix #326

### CODE REVIEW

**Comment by teohhanhui** [comment]
@vbourdeix Can you verify if this fixes the issue for you?

**Comment by teohhanhui** [comment]
Ok, we need someone to try this out on Windows. :smile:

**Comment by Bwen** [comment]
I had this problem and after changing to LF all the .sh scripts everything was fine.
https://files.slack.com/files-pri/T39U3FUKV-F5RSU97RB/apiplateform1.png

It couldnt find the shebang because of the CRLF

I'll test with this fix. I'm on Windows 10 Hyper-V, Docker 17.03.1-ce-win12 (12058)

**Comment by Bwen** [comment]
Confirmed, fix works :)

**Comment by dunglas** [comment]
Thank you very much @teohhanhui!

**Pull request merged**
