### PR TITLE
Better default parameters

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by teohhanhui** [comment]
:+1:

**Comment by dunglas** [comment]
Is is safe for Docker @sroze @teohhanhui

**Comment by teohhanhui** [comment]
We should use [env_file](https://docs.docker.com/compose/compose-file/#env-file) or [environment](https://docs.docker.com/compose/compose-file/#environment) in docker-compose.yml, in conjunction with https://github.com/Incenteev/ParameterHandler

**Comment by teohhanhui** [comment]
http://12factor.net/config

**Pull request merged**
