### PR TITLE
feat: add ld+json encoding

### LINKED ISSUE #2637: ld-json not encoded by Caddyfile
**API Platform version(s) affected**: latest

**Description**  
When making ld-json call, it isn't encoded.

**How to reproduce**  
Call an api route above 500 bytes (minimum encoding size) and check headers. Content-Encoding is missing.

**Possible Solution**  
Edit the caddyfile (pr incoming)

**Additional Context**  
Before and after the change
image

### PR DESCRIPTION
**Pull request by vasilvestre**
I'm not sure if this is a fix or new feature

| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | Closes #2637
| License       | MIT

### CODE REVIEW

**Comment by dunglas** [comment]
I fixed this in Caddy directly: https://github.com/caddyserver/caddy/pull/6081

Maybe can we just wait for a new Caddy tag?

**Comment by vasilvestre** [comment]
> I fixed this in Caddy directly: [caddyserver/caddy#6081](https://github.com/caddyserver/caddy/pull/6081)
> 
> Maybe can we just wait for a new Caddy tag?

Depending of how long Caddy takes to tag, maybe it's better to merge and remove the configuration when it's done ? Or you may comment the issue so people could find a workaround until the next apip release

**Comment by dunglas** [comment]
Let's merge for now!

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thank you Valentin

**Pull request merged**
