### PR TITLE
Use 2.3 for behatch/contexts

### PR DESCRIPTION
**Pull request by blazarecki**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | no
| License       | MIT
| Doc PR        | no

### CODE REVIEW

**Comment by sroze** [comment]
I would prefer to remove this dependency, and remove it from the `behat.yml` file.

**Comment by dunglas** [comment]
@sroze Why? AFAIK there is no better alternative out yet.

**Comment by theofidry** [comment]
Even if we do consider moving away from it, in the meantime it won't hurt to used a fixed version instead of `dev-master`.

**Comment by sroze** [comment]
Yup, that won't hurt. 

@blazarecki could you rebase on `master` ?

**Comment by blazarecki** [comment]
@sroze Done.

**Comment by dunglas** [comment]
Thanks @blazarecki

**Pull request merged**
